remote_theme: just-the-docs/just-the-docs
title: Human among Humans
description: A systems-thinking perspective on individual and collective human behaviour, information systems and social design
author: Omkar Killarikar
plugins:
  - jekyll-seo-tag
color_scheme: dark
ga_tracking: G-8L87470RTE
ga_tracking_anonymize_ip: true
aux_links:
  "GitHub":
    - "https://github.com/seeThroughThis/seeThroughThis.github.io"
  "LinkedIn":
    - "https://www.linkedin.com/in/omkar-killarikar/"

aux_links_new_tab: true
